/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import controllers.Chavoso;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;

/**
 *
 * @author elias
 */
public class Administracao extends javax.swing.JFrame {

    /**
     * Creates new form Administracao
     */
   private static Administracao p;
    
    public static Administracao getInstancia(){
        if(p == null){
            p = new Administracao();
        }
        return p;
    }
    
    public static JDesktopPane getPainel(){
        return getInstancia().jdpprincipal2;
    }
    
    
    /**
     * Creates new form PrincipalChavoso
     */
    public Administracao() {
        initComponents();
        setIcon();
        Chavoso.setGerenciador(jdpprincipal2);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHeader = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_cad_dep = new javax.swing.JLabel();
        btn_cad_lab = new javax.swing.JLabel();
        btn_cad_pessoa = new javax.swing.JLabel();
        btn_upd_lab = new javax.swing.JLabel();
        btn_upd_pessoa = new javax.swing.JLabel();
        btn_administracao = new javax.swing.JLabel();
        btn_upd_dep = new javax.swing.JLabel();
        btn_exit1 = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/chavosoadm.png"));
        Image image = icon.getImage();
        jdpprincipal2 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);

            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Chavoso - Administração");
        setUndecorated(true);
        setResizable(false);

        jpHeader.setBackground(new java.awt.Color(241, 91, 77));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema Chavoso™ - ADMINISTRAÇÃO");

        btn_cad_dep.setBackground(new java.awt.Color(45, 45, 45));
        btn_cad_dep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cad_dep.setForeground(new java.awt.Color(255, 255, 255));
        btn_cad_dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cad_dep.setText("Cadastrar departamento");
        btn_cad_dep.setOpaque(true);
        btn_cad_dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cad_depMouseClicked(evt);
            }
        });

        btn_cad_lab.setBackground(new java.awt.Color(45, 45, 45));
        btn_cad_lab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cad_lab.setForeground(new java.awt.Color(255, 255, 255));
        btn_cad_lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cad_lab.setText("Cadastrar laboratório");
        btn_cad_lab.setOpaque(true);
        btn_cad_lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cad_labMouseClicked(evt);
            }
        });

        btn_cad_pessoa.setBackground(new java.awt.Color(45, 45, 45));
        btn_cad_pessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cad_pessoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_cad_pessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cad_pessoa.setText("Cadastrar pessoa");
        btn_cad_pessoa.setOpaque(true);
        btn_cad_pessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cad_pessoaMouseClicked(evt);
            }
        });

        btn_upd_lab.setBackground(new java.awt.Color(45, 45, 45));
        btn_upd_lab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_upd_lab.setForeground(new java.awt.Color(255, 255, 255));
        btn_upd_lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_upd_lab.setText("Editar laboratório");
        btn_upd_lab.setOpaque(true);
        btn_upd_lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_upd_labMouseClicked(evt);
            }
        });

        btn_upd_pessoa.setBackground(new java.awt.Color(45, 45, 45));
        btn_upd_pessoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_upd_pessoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_upd_pessoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_upd_pessoa.setText("Editar pessoa");
        btn_upd_pessoa.setOpaque(true);
        btn_upd_pessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_upd_pessoaMouseClicked(evt);
            }
        });

        btn_administracao.setBackground(new java.awt.Color(45, 45, 45));
        btn_administracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_administracao.setForeground(new java.awt.Color(255, 255, 255));
        btn_administracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_administracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        btn_administracao.setOpaque(true);
        btn_administracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_administracaoMouseClicked(evt);
            }
        });

        btn_upd_dep.setBackground(new java.awt.Color(45, 45, 45));
        btn_upd_dep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_upd_dep.setForeground(new java.awt.Color(255, 255, 255));
        btn_upd_dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_upd_dep.setText("Editar departamento");
        btn_upd_dep.setOpaque(true);
        btn_upd_dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_upd_depMouseClicked(evt);
            }
        });

        btn_exit1.setBackground(new java.awt.Color(84, 84, 84));
        btn_exit1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_exit1.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit1.setText("X");
        btn_exit1.setOpaque(true);
        btn_exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exit1MouseClicked(evt);
            }
        });

        btn_minimizar.setBackground(new java.awt.Color(84, 84, 84));
        btn_minimizar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimizar.setText("-");
        btn_minimizar.setOpaque(true);
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btn_cad_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cad_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cad_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_upd_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_upd_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_upd_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_administracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpHeaderLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_administracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_upd_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_upd_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_upd_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cad_dep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cad_pessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_cad_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addComponent(btn_exit1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jdpprincipal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdpprincipal2.setAutoscrolls(true);
        jdpprincipal2.setPreferredSize(new java.awt.Dimension(1182, 600));

        javax.swing.GroupLayout jdpprincipal2Layout = new javax.swing.GroupLayout(jdpprincipal2);
        jdpprincipal2.setLayout(jdpprincipal2Layout);
        jdpprincipal2Layout.setHorizontalGroup(
            jdpprincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1261, Short.MAX_VALUE)
        );
        jdpprincipal2Layout.setVerticalGroup(
            jdpprincipal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpprincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 1263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpprincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cad_depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cad_depMouseClicked
        // TODO add your handling code here
        Chavoso.gerenciarJanelas(new CadastroDepartamento());
    }//GEN-LAST:event_btn_cad_depMouseClicked

    private void btn_cad_labMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cad_labMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "Clicado");
        Chavoso.gerenciarJanelas(new CadastroLaboratorio());
    }//GEN-LAST:event_btn_cad_labMouseClicked

    private void btn_cad_pessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cad_pessoaMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new CadastroPessoa());
    }//GEN-LAST:event_btn_cad_pessoaMouseClicked

    private void btn_upd_labMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_upd_labMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new EditarLaboratorio());
    }//GEN-LAST:event_btn_upd_labMouseClicked

    private void btn_upd_pessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_upd_pessoaMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new EditarPessoa());
    }//GEN-LAST:event_btn_upd_pessoaMouseClicked

    private void btn_administracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administracaoMouseClicked
        // TODO add your handling code here:
        Chavoso.entrarMenu();
        this.dispose();
    }//GEN-LAST:event_btn_administracaoMouseClicked

    private void btn_upd_depMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_upd_depMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new EditarDepartamento());
    }//GEN-LAST:event_btn_upd_depMouseClicked

    private void btn_exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exit1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exit1MouseClicked

    private void btn_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseClicked
        // TODO add your handling code here:
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_btn_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracao().setVisible(true);
            }
        });
    }

    private void setIcon() {
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_administracao;
    private javax.swing.JLabel btn_cad_dep;
    private javax.swing.JLabel btn_cad_lab;
    private javax.swing.JLabel btn_cad_pessoa;
    private javax.swing.JLabel btn_exit1;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel btn_upd_dep;
    private javax.swing.JLabel btn_upd_lab;
    private javax.swing.JLabel btn_upd_pessoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpprincipal;
    private javax.swing.JDesktopPane jdpprincipal1;
    private javax.swing.JDesktopPane jdpprincipal2;
    private javax.swing.JPanel jpHeader;
    // End of variables declaration//GEN-END:variables
}
