/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;
import Ententys.Departamento;
import Ententys.Laboratorio;
import controllers.Chavoso;
import models.DAODepartamento;
import models.DAOLaboratorio;

/**
 *
 * @author David Alysson
 */
public class AlterarEstado extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlterarEstado
     */
    public AlterarEstado() {
        initComponents();
        for(Departamento d: Chavoso.getDeps()){
            cbDep.addItem(d);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbDep = new javax.swing.JComboBox<>();
        cbLab = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtmotivo = new javax.swing.JLabel();
        txtacao = new javax.swing.JTextField();
        btn_Alterar = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Alterar Estado Laboratório");

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(241, 91, 77));
        jLabel1.setText("Departamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        cbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepItemStateChanged(evt);
            }
        });
        jPanel1.add(cbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 240, -1));

        cbLab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbLab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLabItemStateChanged(evt);
            }
        });
        jPanel1.add(cbLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 240, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 91, 77));
        jLabel2.setText("Laboratório");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        cbEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ocupado", "disponivel" }));
        cbEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEstadoItemStateChanged(evt);
            }
        });
        jPanel1.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 240, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 91, 77));
        jLabel3.setText("Estado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        txtmotivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtmotivo.setForeground(new java.awt.Color(241, 91, 77));
        txtmotivo.setText("Motivo");
        jPanel1.add(txtmotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        txtacao.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 240, -1));

        btn_Alterar.setBackground(new java.awt.Color(245, 88, 71));
        btn_Alterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Alterar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Alterar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Alterar.setText("Alterar");
        btn_Alterar.setOpaque(true);
        btn_Alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AlterarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLabItemStateChanged
        // TODO add DAODepartamento dao = new DAODepartamento();
    }//GEN-LAST:event_cbLabItemStateChanged

    private void cbDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepItemStateChanged
        // TODO add your handling code here:
        cbLab.removeAllItems();
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int id = Chavoso.PegarIdDep(dep);
        for(Laboratorio l: Chavoso.buscaLab(id)){
            cbLab.addItem(l.getNumero());
        }
    }//GEN-LAST:event_cbDepItemStateChanged

    private void cbEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEstadoItemStateChanged
        // TODO add your handling code here:
        if(cbEstado.getSelectedItem().equals("disponivel")){
            txtacao.setVisible(false);
            txtmotivo.setVisible(false);
        }else{
            txtacao.setVisible(true);
            txtmotivo.setVisible(true);
        }
    }//GEN-LAST:event_cbEstadoItemStateChanged

    private void btn_AlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AlterarMouseClicked
        // TODO add your handling code here:
         Departamento dep = (Departamento) cbDep.getSelectedItem();
        int id = Chavoso.PegarIdDep(dep);
        int num = Integer.parseInt(cbLab.getSelectedItem().toString());
        String estado = (String) cbEstado.getSelectedItem();
        String acao;
        if(!cbEstado.getSelectedItem().equals(Chavoso.Disponibiblidade(id, num))){
        if(cbEstado.getSelectedItem().equals("disponivel")){
            acao = "Chave com o Administrador";
        }else{
            acao = txtacao.getText();
        }
        if(acao.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Campo não preenchido!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
        }else{
            Chavoso.AlterarDisponibiliade(estado, id, num, acao,true);
            JOptionPane.showMessageDialog(rootPane, "Alterado Com Sucesso!", "AVISO", JOptionPane.INFORMATION_MESSAGE, null);
        }
        }else{
           JOptionPane.showMessageDialog(rootPane, "Laboratório já está nesse estado", "AVISO", JOptionPane.ERROR_MESSAGE, null); 
        }
    }//GEN-LAST:event_btn_AlterarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Alterar;
    private javax.swing.JComboBox<Object> cbDep;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<Object> cbLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtacao;
    private javax.swing.JLabel txtmotivo;
    // End of variables declaration//GEN-END:variables
}
