/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import controllers.Chavoso;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alysson
 */
public class AssinaturaLimpeza extends javax.swing.JInternalFrame {

    /**
     * Creates new form Assinatura
     */
    public AssinaturaLimpeza() {
        initComponents();
        txtsenha.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtestado = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        txtsenha = new javax.swing.JPasswordField();
        lb_laboratorio1 = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Insira a assinatura!");

        txtestado.setEnabled(false);

        txtid.setEnabled(false);

        txtNum.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtsenha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 230, -1));

        lb_laboratorio1.setBackground(new java.awt.Color(0, 0, 0));
        lb_laboratorio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_laboratorio1.setForeground(new java.awt.Color(241, 91, 77));
        lb_laboratorio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_laboratorio1.setText("ASSINATURA");
        jPanel1.add(lb_laboratorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, -1));

        btn_confirmar.setBackground(new java.awt.Color(241, 91, 77));
        btn_confirmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_confirmar.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_confirmar.setText("Confirmar");
        btn_confirmar.setOpaque(true);
        btn_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtid)
                        .addComponent(txtNum)))
                .addContainerGap(392, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmarMouseClicked
        // TODO add your handling code here:
        String senha = new String(txtsenha.getPassword());
        String estado = txtestado.getText();
        int id = Integer.parseInt(txtid.getText());
        int num = Integer.parseInt(txtNum.getText());
        String acao = "Laboratório em Limpeza";
        int idpessoa = Chavoso.getIdBySenha(senha);
        if(Chavoso.VerificaPessoaLimpeza(idpessoa)){
        if(Chavoso.VerificarAssinaturaLimpeza(senha,estado,id,num,acao)){
            JOptionPane.showMessageDialog(rootPane, "Chave Entregue!", "AVISO", JOptionPane.INFORMATION_MESSAGE, null);
            Chavoso.relatorio.setVerificacao_senha(true);
            this.dispose();
        }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Pessoa não é da Limpeza ou Assinatura Inválida!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btn_confirmarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_confirmar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_laboratorio1;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
    
    public void recebendo(String estado,int id , int num){
        txtestado.setText(estado);
        txtNum.setText(Integer.toString(num));
        txtid.setText(Integer.toString(id));
    }
}


