/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static javax.management.Query.lt;
import javax.swing.table.DefaultTableModel;
import Ententys.Departamento;
import Ententys.Laboratorio;
import controllers.Chavoso;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import models.DAODepartamento;
import models.DAOLaboratorio;

/**
 *
 * @author David Alysson
 */
public class BuscaLab extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaLab
     */
    public BuscaLab() {
        initComponents();
        
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        ((DefaultTableCellRenderer)jtLaboratorio.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
        JTableHeader Theader = jtLaboratorio.getTableHeader();
        Theader.setBackground(new Color(0,0,0,0));
        Theader.setOpaque(false);
        Theader.setForeground(new Color(0,0,0));
        Theader.setFont(new Font("Arial" , Font.BOLD , 14));
    
        for(Departamento d: Chavoso.getDeps()){
            cbDep.addItem(d);
        }
    }
    
    public void mostrar(int id) {
        Chavoso.gerarTabelaDeps(jtLaboratorio, id);
    }
    
    public void limpar(){
        Chavoso.limparTabela(jtLaboratorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbDep = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLaboratorio = new javax.swing.JTable();
        btn_buscar = new javax.swing.JLabel();
        btn_limpar = new javax.swing.JLabel();
        btn_entregar_chave3 = new javax.swing.JLabel();
        btn_Alterar_Estado = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Buscar Laboratório");
        setPreferredSize(new java.awt.Dimension(912, 384));

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepActionPerformed(evt);
            }
        });
        jPanel1.add(cbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 290, -1));

        jtLaboratorio.setBackground(new java.awt.Color(214, 217, 223));
        jtLaboratorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtLaboratorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtLaboratorio.setForeground(new java.awt.Color(0, 0, 102));
        jtLaboratorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DEPARTAMENTO", "NÚMERO LABORATÓRIO", "NÚMERO CHAVE", "DISPONIBILIDADE", "DESCRIÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLaboratorio.setGridColor(new java.awt.Color(255, 255, 255));
        jtLaboratorio.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jtLaboratorio.setSelectionForeground(new java.awt.Color(0, 0, 102));
        jtLaboratorio.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtLaboratorio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 830, 190));

        btn_buscar.setBackground(new java.awt.Color(241, 91, 77));
        btn_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buscar.setText("Buscar");
        btn_buscar.setOpaque(true);
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 110, -1));

        btn_limpar.setBackground(new java.awt.Color(241, 91, 77));
        btn_limpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_limpar.setText("Limpar");
        btn_limpar.setOpaque(true);
        btn_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limparMouseClicked(evt);
            }
        });
        jPanel1.add(btn_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 120, -1));

        btn_entregar_chave3.setBackground(new java.awt.Color(0, 0, 0));
        btn_entregar_chave3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_entregar_chave3.setForeground(new java.awt.Color(241, 91, 77));
        btn_entregar_chave3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_entregar_chave3.setText("DEPARTAMENTO");
        jPanel1.add(btn_entregar_chave3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, -1));

        btn_Alterar_Estado.setBackground(new java.awt.Color(241, 91, 77));
        btn_Alterar_Estado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Alterar_Estado.setForeground(new java.awt.Color(255, 255, 255));
        btn_Alterar_Estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Alterar_Estado.setText("Alterar Estado");
        btn_Alterar_Estado.setOpaque(true);
        btn_Alterar_Estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Alterar_EstadoMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Alterar_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepActionPerformed

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
        Departamento d = (Departamento) cbDep.getSelectedItem();
        int iddep = Chavoso.PegarIdDep(d);
        mostrar(iddep);
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseClicked
        // TODO add your handling code here:
         limpar();
    }//GEN-LAST:event_btn_limparMouseClicked

    private void btn_Alterar_EstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Alterar_EstadoMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new AlterarEstado());
        this.dispose();
    }//GEN-LAST:event_btn_Alterar_EstadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Alterar_Estado;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_entregar_chave3;
    private javax.swing.JLabel btn_limpar;
    private javax.swing.JComboBox<Object> cbDep;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtLaboratorio;
    // End of variables declaration//GEN-END:variables
}
