/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Ententys.Departamento;
import controllers.Chavoso;
import javax.swing.JOptionPane;


/**
 *
 * @author David Alysson
 */
public class CadastroPessoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadastropessoa
     */
    public CadastroPessoa() {
        initComponents();
        
        for(Departamento d: Chavoso.getDeps()){
            cmbDep.addItem(d);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        txtdepartamento1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JLabel();
        cmbfuncao = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        cmbDep = new javax.swing.JComboBox<>();
        txtdepartamento = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();

        setClosable(true);
        setTitle("Cadastro Pessoa");

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNome.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 115, 462, -1));

        txtdepartamento1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento1.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento1.setText("Função:");
        jPanel1.add(txtdepartamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 19, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 91, 77));
        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 84, -1, -1));

        btn_cadastrar.setBackground(new java.awt.Color(245, 88, 71));
        btn_cadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.setOpaque(true);
        btn_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cadastrarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, -1));

        cmbfuncao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbfuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Auxiliar de limpeza", "Administrador" }));
        cmbfuncao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbfuncaoItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbfuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 50, 462, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 91, 77));
        jLabel6.setText("CPF:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 146, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 91, 77));
        jLabel7.setText("Senha:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 146, -1, -1));

        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###########");  
            txtCPF = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        txtCPF.setBackground(new java.awt.Color(204, 204, 204));
        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 177, 165, -1));

        cmbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDepItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 319, -1));

        txtdepartamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento.setText("Departamento:");
        jPanel1.add(txtdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        txtsenha.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 177, 218, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDepItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepItemStateChanged

    private void cmbfuncaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbfuncaoItemStateChanged
        // TODO add your handling code here:
        if(!cmbfuncao.getSelectedItem().equals("Professor")){
            cmbDep.setVisible(false);
            txtdepartamento.setVisible(false);
        }else{
            cmbDep.setVisible(true);
            txtdepartamento.setVisible(true);
        }
    }//GEN-LAST:event_cmbfuncaoItemStateChanged

    private void btn_cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadastrarMouseClicked
        // TODO add your handling code here:
        String senha = new String(txtsenha.getPassword());
        Chavoso.cadastrarPessoa(senha,txtNome.getText(),txtCPF.getText(),cmbfuncao.getSelectedItem().toString(),cmbDep.getSelectedItem().toString());
        limpar();
    }//GEN-LAST:event_btn_cadastrarMouseClicked
    
    public void limpar(){
        txtNome.setText("");
        txtCPF.setText("");
        txtsenha.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_cadastrar;
    private javax.swing.JComboBox<Object> cmbDep;
    private javax.swing.JComboBox<Object> cmbfuncao;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtdepartamento;
    private javax.swing.JLabel txtdepartamento1;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
