/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Ententys.Pessoa;
import controllers.Chavoso;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alysson
 */
public class EditarPessoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarLaboratorio
     */
    public EditarPessoa() {
        initComponents();
        buscar();
    }
    
    public void limpar(){
        txtNome.setText("");
        txtCPF.setText("");
        txtsenha.setText("");
        txtCPFBusca.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCPFBusca = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        txtsenha = new javax.swing.JTextField();
        txtdepartamento4 = new javax.swing.JLabel();
        btn_editar1 = new javax.swing.JLabel();
        txtdepartamento5 = new javax.swing.JLabel();
        txtdepartamento6 = new javax.swing.JLabel();
        txtdepartamento7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Editar Pessoa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###########");  
            txtCPFBusca = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        txtCPFBusca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFBuscaFocusLost(evt);
            }
        });
        txtCPFBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFBuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFBuscaKeyReleased(evt);
            }
        });
        jPanel1.add(txtCPFBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 580, 30));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 420, 30));

        try{  
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("###########");  
            txtCPF = new javax.swing.JFormattedTextField(data);  
        }  
        catch (Exception e){  
        }
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 278, 30));
        jPanel1.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 278, 30));

        txtdepartamento4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento4.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento4.setText("Digite o CPF:");
        jPanel1.add(txtdepartamento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btn_editar1.setBackground(new java.awt.Color(245, 88, 71));
        btn_editar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_editar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editar1.setText("Atualizar");
        btn_editar1.setOpaque(true);
        btn_editar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editar1MouseClicked(evt);
            }
        });
        jPanel1.add(btn_editar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 140, -1));

        txtdepartamento5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento5.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento5.setText("Senha");
        jPanel1.add(txtdepartamento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        txtdepartamento6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento6.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento6.setText("Nome");
        jPanel1.add(txtdepartamento6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        txtdepartamento7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento7.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento7.setText("CPF");
        jPanel1.add(txtdepartamento7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed
    
    private void buscar(){
        List<Pessoa> lista = Chavoso.getPessoas(txtCPFBusca.getText());
        if(lista.size() == 0){
            txtNome.setText("");
            txtCPF.setText("");
            txtsenha.setText("");
            txtNome.setFocusable(false);
            txtCPF.setFocusable(false);
            txtsenha.setFocusable(false);
        }
        for(Pessoa p : lista){
            txtNome.setText(p.getNome());
            txtCPF.setText(p.getCpf());
            txtsenha.setText(p.getSenha());
            txtNome.setFocusable(true);
            txtCPF.setFocusable(true);
            txtsenha.setFocusable(true);
        }
    }
    private void txtCPFBuscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFBuscaFocusLost
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtCPFBuscaFocusLost

    private void txtCPFBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFBuscaKeyPressed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtCPFBuscaKeyPressed

    private void txtCPFBuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFBuscaKeyReleased
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtCPFBuscaKeyReleased

    private void btn_editar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editar1MouseClicked
        // TODO add your handling code here:
        if(Chavoso.editarPessoa(txtNome.getText(),txtsenha.getText(),txtCPF.getText(),txtCPFBusca.getText())){
            this.dispose();
        }
        limpar();
    }//GEN-LAST:event_btn_editar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_editar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtCPFBusca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtdepartamento4;
    private javax.swing.JLabel txtdepartamento5;
    private javax.swing.JLabel txtdepartamento6;
    private javax.swing.JLabel txtdepartamento7;
    private javax.swing.JTextField txtsenha;
    // End of variables declaration//GEN-END:variables
}
