/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Ententys.Departamento;
import Ententys.Laboratorio;
import controllers.Chavoso;
import javax.swing.JOptionPane;

/**
 *
 * @author David Alysson
 */
public class EditarLaboratorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarPessoa
     */
    public EditarLaboratorio() {
        initComponents();
        txtnum.grabFocus();
 
        for(Departamento d: Chavoso.getDeps()){
            cbDep.addItem(d);
        }
        
        for(Departamento d: Chavoso.getDeps()){
            cmbDep.addItem(d);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbDep = new javax.swing.JComboBox<>();
        cbLab = new javax.swing.JComboBox<>();
        txtnum = new javax.swing.JTextField();
        cmbDep = new javax.swing.JComboBox<>();
        btn_editar = new javax.swing.JLabel();
        txtdepartamento1 = new javax.swing.JLabel();
        txtdepartamento2 = new javax.swing.JLabel();
        txtdepartamento3 = new javax.swing.JLabel();
        txtdepartamento4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Editar Laboratorio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));

        cbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepItemStateChanged(evt);
            }
        });

        cbLab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtnum.setBackground(new java.awt.Color(204, 204, 204));

        btn_editar.setBackground(new java.awt.Color(245, 88, 71));
        btn_editar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editar.setText("Atualizar");
        btn_editar.setOpaque(true);
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });

        txtdepartamento1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento1.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento1.setText("Novo departamento?");

        txtdepartamento2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento2.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento2.setText("Novo número?");

        txtdepartamento3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento3.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento3.setText("Departamento");

        txtdepartamento4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtdepartamento4.setForeground(new java.awt.Color(241, 91, 77));
        txtdepartamento4.setText("Laboratório");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(txtdepartamento3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtdepartamento4)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cbDep, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cbLab, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtdepartamento1)
                .addGap(130, 130, 130))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(txtdepartamento2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(222, 222, 222)
                    .addComponent(jLabel1)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdepartamento3)
                    .addComponent(txtdepartamento4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLab, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(txtdepartamento2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdepartamento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_editar)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jLabel1)
                    .addContainerGap(229, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 336));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepItemStateChanged
        // TODO add your handling code here:
        cbLab.removeAllItems();
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int iddep = Chavoso.PegarIdDep(dep);
        for(Laboratorio l: Chavoso.buscaLab(iddep)){
            cbLab.addItem(l.getNumero());
        }
        String num = cbLab.getSelectedItem().toString();
        txtnum.setText(num);
    }//GEN-LAST:event_cbDepItemStateChanged

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        // TODO add your handling code here:
         if(Chavoso.editarLaboratorio((txtnum.getText()), Chavoso.PegarIdDep((Departamento) cmbDep.getSelectedItem()) , Chavoso.PegarIdDep((Departamento) cbDep.getSelectedItem()) , Integer.parseInt(cbLab.getSelectedItem().toString()))){
            this.dispose();
        }
    }//GEN-LAST:event_btn_editarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_editar;
    private javax.swing.JComboBox<Object> cbDep;
    private javax.swing.JComboBox<Object> cbLab;
    private javax.swing.JComboBox<Object> cmbDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtdepartamento1;
    private javax.swing.JLabel txtdepartamento2;
    private javax.swing.JLabel txtdepartamento3;
    private javax.swing.JLabel txtdepartamento4;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
