/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;
import Ententys.Departamento;
import Ententys.Laboratorio;
import controllers.Chavoso;
import models.DAODepartamento;
import models.DAOLaboratorio;

/**
 *
 * @author David Alysson
 */
public class EntregarChave extends javax.swing.JInternalFrame {

    /**
     * Creates new form EntregarChave
     */
    public EntregarChave() {
        initComponents();
    
    for(Departamento d: Chavoso.getDeps()){
            cbDep.addItem(d);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cbDep = new javax.swing.JComboBox<>();
        cbLab = new javax.swing.JComboBox<>();
        lb_dep = new javax.swing.JLabel();
        lb_laboratorio = new javax.swing.JLabel();
        btn_entregar = new javax.swing.JLabel();
        btnLimpeza = new javax.swing.JRadioButton();
        btnAula = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Entregar Chave");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepItemStateChanged(evt);
            }
        });
        jPanel1.add(cbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 280, -1));

        cbLab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbLab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLabItemStateChanged(evt);
            }
        });
        jPanel1.add(cbLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, -1));

        lb_dep.setBackground(new java.awt.Color(255, 255, 255));
        lb_dep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_dep.setForeground(new java.awt.Color(245, 88, 71));
        lb_dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dep.setText("DEPARTAMENTO");
        jPanel1.add(lb_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, -1));

        lb_laboratorio.setBackground(new java.awt.Color(45, 45, 45));
        lb_laboratorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_laboratorio.setForeground(new java.awt.Color(245, 88, 71));
        lb_laboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_laboratorio.setText("LABORATÓRIO");
        jPanel1.add(lb_laboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 120, -1));

        btn_entregar.setBackground(new java.awt.Color(245, 88, 71));
        btn_entregar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_entregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_entregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_entregar.setText("Entregar");
        btn_entregar.setOpaque(true);
        btn_entregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_entregarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_entregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 120, -1));

        btnLimpeza.setBackground(new java.awt.Color(33, 34, 36));
        buttonGroup1.add(btnLimpeza);
        btnLimpeza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpeza.setForeground(new java.awt.Color(245, 88, 71));
        btnLimpeza.setText("Limpeza");
        jPanel1.add(btnLimpeza, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        btnAula.setBackground(new java.awt.Color(33, 34, 36));
        buttonGroup1.add(btnAula);
        btnAula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAula.setForeground(new java.awt.Color(245, 88, 71));
        btnAula.setText("Aula");
        jPanel1.add(btnAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_entregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entregarMouseClicked
        // TODO add your handling code here:
        if(btnAula.isSelected()){
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int iddep = Chavoso.PegarIdDep(dep);
        int num = Integer.parseInt(cbLab.getSelectedItem().toString());
        if (!Chavoso.entregarChave(iddep, num)){
            JOptionPane.showMessageDialog(rootPane, "Laboratorio Ocupado ou em Manutenção!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
        }
        this.dispose();
        }
        if(btnLimpeza.isSelected()){
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int iddep = Chavoso.PegarIdDep(dep);
        int num = Integer.parseInt(cbLab.getSelectedItem().toString());
        if (!Chavoso.entregarChavelimpeza(iddep, num)){
            JOptionPane.showMessageDialog(rootPane, "Laboratorio Ocupado ou em Manutenção!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
        }
        this.dispose();
        }
        if(!btnAula.isSelected() && !btnLimpeza.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "Nenhuma opção selecionada!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btn_entregarMouseClicked

    private void cbLabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLabItemStateChanged
        // TODO add DAODepartamento dao = new DAODepartamento();
    }//GEN-LAST:event_cbLabItemStateChanged

    private void cbDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepItemStateChanged
        // TODO add your handling code here:
        cbLab.removeAllItems();
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int iddep = Chavoso.PegarIdDep(dep);
        for(Laboratorio l: Chavoso.buscaLab(iddep)){
            cbLab.addItem(l.getNumero());
        }
    }//GEN-LAST:event_cbDepItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAula;
    private javax.swing.JRadioButton btnLimpeza;
    private javax.swing.JLabel btn_entregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Object> cbDep;
    private javax.swing.JComboBox<Object> cbLab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_dep;
    private javax.swing.JLabel lb_laboratorio;
    // End of variables declaration//GEN-END:variables
}
