/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Ententys.Departamento;
import controllers.Chavoso;
import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

/**
 *
 * @author David Alysson
 */
public class Historico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Historico
     */
    public Historico() {
        initComponents();
        
        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        ((DefaultTableCellRenderer)jtbrelatorio.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
        JTableHeader Theader = jtbrelatorio.getTableHeader();
        Theader.setBackground(new Color(0,0,0,0));
        Theader.setOpaque(false);
        Theader.setForeground(new Color(0,0,0));
        Theader.setFont(new Font("Arial" , Font.BOLD , 14));
        
        for(Departamento d: Chavoso.getDeps()){
            cbDep.addItem(d);
        }
    }
    
    public void mostrar(int id) {
        Chavoso.gerarTabelaHistorico(jtbrelatorio, id);
    }
    
    public void limpar(){
        Chavoso.limparTabela(jtbrelatorio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbrelatorio = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_entregar_chave3 = new javax.swing.JLabel();
        cbDep = new javax.swing.JComboBox<>();
        btn_limpar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Histórico");
        setPreferredSize(new java.awt.Dimension(912, 384));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(912, 384));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbrelatorio.setBackground(new java.awt.Color(214, 217, 223));
        jtbrelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtbrelatorio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jtbrelatorio.setForeground(new java.awt.Color(0, 0, 102));
        jtbrelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chave", "Nome Autor", "Nome Admin", "Verificação", "Estado", "Data / Hora", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbrelatorio.setGridColor(new java.awt.Color(255, 255, 255));
        jtbrelatorio.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jtbrelatorio.setSelectionForeground(new java.awt.Color(0, 0, 102));
        jtbrelatorio.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbrelatorio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 190));

        jPanel2.setBackground(new java.awt.Color(33, 34, 36));

        btn_entregar_chave3.setBackground(new java.awt.Color(0, 0, 0));
        btn_entregar_chave3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_entregar_chave3.setForeground(new java.awt.Color(245, 88, 71));
        btn_entregar_chave3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_entregar_chave3.setText("DEPARTAMENTO");

        cbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepActionPerformed(evt);
            }
        });

        btn_limpar.setBackground(new java.awt.Color(245, 88, 71));
        btn_limpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_limpar.setForeground(new java.awt.Color(255, 255, 255));
        btn_limpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_limpar.setText("Limpar");
        btn_limpar.setOpaque(true);
        btn_limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limparMouseClicked(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(245, 88, 71));
        btn_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_buscar.setText("Buscar");
        btn_buscar.setOpaque(true);
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbDep, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(btn_entregar_chave3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 356, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_entregar_chave3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar)
                    .addComponent(btn_buscar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepActionPerformed

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
        Departamento d = (Departamento) cbDep.getSelectedItem();
        int iddep = Chavoso.PegarIdDep(d);
        mostrar(iddep);
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void btn_limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limparMouseClicked
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_btn_limparMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_entregar_chave3;
    private javax.swing.JLabel btn_limpar;
    private javax.swing.JComboBox<Object> cbDep;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbrelatorio;
    // End of variables declaration//GEN-END:variables
}
