/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;
import Ententys.Departamento;
import Ententys.Laboratorio;
import controllers.Chavoso;
import models.DAODepartamento;
import models.DAOLaboratorio;

/**
 *
 * @author David Alysson
 */
public class Manutencao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Manuntenção
     */
    public Manutencao() {
        initComponents();
        txt_encerrar.setVisible(false);
        btn_confirmar_Encerramento.setVisible(false);
        btn_Cancelar_Encerramento.setVisible(false);
        for(Departamento d: Chavoso.getDeps()){
            cbDep.addItem(d);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cbDep = new javax.swing.JComboBox<>();
        cbLab = new javax.swing.JComboBox<>();
        chkDispo = new javax.swing.JCheckBox();
        txtacao = new javax.swing.JTextField();
        lb_dep = new javax.swing.JLabel();
        lb_laboratorio = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JLabel();
        lb_laboratorio1 = new javax.swing.JLabel();
        txt_encerrar = new javax.swing.JLabel();
        btn_confirmar_Encerramento = new javax.swing.JLabel();
        btn_Cancelar_Encerramento = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Manutenção");

        jPanel1.setBackground(new java.awt.Color(33, 34, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbDep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbDep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDepItemStateChanged(evt);
            }
        });
        cbDep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbDepMouseClicked(evt);
            }
        });
        jPanel1.add(cbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 280, -1));

        cbLab.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbLab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLabItemStateChanged(evt);
            }
        });
        jPanel1.add(cbLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 280, -1));

        chkDispo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        chkDispo.setForeground(new java.awt.Color(241, 91, 77));
        chkDispo.setText("Confirmo que esse laboratório entrará em manutenção.");
        jPanel1.add(chkDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        txtacao.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 280, -1));

        lb_dep.setBackground(new java.awt.Color(45, 45, 45));
        lb_dep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_dep.setForeground(new java.awt.Color(241, 91, 77));
        lb_dep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dep.setText("DEPARTAMENTO");
        jPanel1.add(lb_dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, -1));

        lb_laboratorio.setBackground(new java.awt.Color(45, 45, 45));
        lb_laboratorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_laboratorio.setForeground(new java.awt.Color(241, 91, 77));
        lb_laboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_laboratorio.setText("MOTIVO");
        jPanel1.add(lb_laboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 120, -1));

        btn_confirmar.setBackground(new java.awt.Color(241, 91, 77));
        btn_confirmar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_confirmar.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_confirmar.setText("Confirmar");
        btn_confirmar.setOpaque(true);
        btn_confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 120, -1));

        lb_laboratorio1.setBackground(new java.awt.Color(45, 45, 45));
        lb_laboratorio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_laboratorio1.setForeground(new java.awt.Color(241, 91, 77));
        lb_laboratorio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_laboratorio1.setText("LABORATÓRIO");
        jPanel1.add(lb_laboratorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 120, -1));

        txt_encerrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_encerrar.setForeground(new java.awt.Color(241, 91, 77));
        txt_encerrar.setText("Deseja encerrar a manuntenção?");
        jPanel1.add(txt_encerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        btn_confirmar_Encerramento.setBackground(new java.awt.Color(0, 150, 62));
        btn_confirmar_Encerramento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_confirmar_Encerramento.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmar_Encerramento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_confirmar_Encerramento.setText("Confirmar");
        btn_confirmar_Encerramento.setOpaque(true);
        btn_confirmar_Encerramento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_confirmar_EncerramentoMouseClicked(evt);
            }
        });
        jPanel1.add(btn_confirmar_Encerramento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 30));

        btn_Cancelar_Encerramento.setBackground(new java.awt.Color(204, 0, 0));
        btn_Cancelar_Encerramento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Cancelar_Encerramento.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancelar_Encerramento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cancelar_Encerramento.setText("Cancelar");
        btn_Cancelar_Encerramento.setOpaque(true);
        btn_Cancelar_Encerramento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Cancelar_EncerramentoMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Cancelar_Encerramento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbDepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDepItemStateChanged
        // TODO add your handling code here:

        cbLab.removeAllItems();
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int id = Chavoso.PegarIdDep(dep);
        for(Laboratorio l: Chavoso.buscaLab(id)){
            cbLab.addItem(l.getNumero());
        }
    }//GEN-LAST:event_cbDepItemStateChanged

    private void cbDepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbDepMouseClicked
        //nada
    }//GEN-LAST:event_cbDepMouseClicked

    private void cbLabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbLabItemStateChanged
        // TODO add DAODepartamento dao = new DAODepartamento();

    }//GEN-LAST:event_cbLabItemStateChanged

    private void btn_confirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmarMouseClicked
        // TODO add your handling code here:
        if(chkDispo.isSelected()){
            int id = Chavoso.PegarIdDep((Departamento) cbDep.getSelectedItem());
            int num = Integer.parseInt(cbLab.getSelectedItem().toString());
            if(txtacao.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Campo não preenchido!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
            }else{
                if(!Chavoso.Disponibiblidade(id,num).equals("manutenção")){
                    Chavoso.manutencao((Departamento) cbDep.getSelectedItem(), txtacao.getText(),id,num,1);
                    JOptionPane.showMessageDialog(rootPane, "Laboratório entrou em Manutenção!", "AVISO", JOptionPane.INFORMATION_MESSAGE, null);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Laboratório já está em manuntenção!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
                    txt_encerrar.setVisible(true);
                    btn_confirmar_Encerramento.setVisible(true);
                    btn_Cancelar_Encerramento.setVisible(true);
                }
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "É exigido uma confirmação!", "AVISO", JOptionPane.ERROR_MESSAGE, null);
        }
    }//GEN-LAST:event_btn_confirmarMouseClicked

    private void btn_confirmar_EncerramentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmar_EncerramentoMouseClicked
        // TODO add your handling code here:
        Departamento dep = (Departamento) cbDep.getSelectedItem();
        int id = Chavoso.PegarIdDep(dep);
        int num = Integer.parseInt(cbLab.getSelectedItem().toString());
        Chavoso.manutencao(dep, "Chave com o Administrador", id, num, 0);
        JOptionPane.showMessageDialog(rootPane, "Manuntenção Encerrada!", "AVISO", JOptionPane.INFORMATION_MESSAGE, null);
        txt_encerrar.setVisible(false);
        btn_confirmar_Encerramento.setVisible(false);
        btn_Cancelar_Encerramento.setVisible(false);
    }//GEN-LAST:event_btn_confirmar_EncerramentoMouseClicked

    private void btn_Cancelar_EncerramentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cancelar_EncerramentoMouseClicked
        // TODO add your handling code here:
        txt_encerrar.setVisible(false);
        btn_confirmar_Encerramento.setVisible(false);
        btn_Cancelar_Encerramento.setVisible(false);
    }//GEN-LAST:event_btn_Cancelar_EncerramentoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Cancelar_Encerramento;
    private javax.swing.JLabel btn_confirmar;
    private javax.swing.JLabel btn_confirmar_Encerramento;
    private javax.swing.JComboBox<Object> cbDep;
    private javax.swing.JComboBox<Object> cbLab;
    private javax.swing.JCheckBox chkDispo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_dep;
    private javax.swing.JLabel lb_laboratorio;
    private javax.swing.JLabel lb_laboratorio1;
    private javax.swing.JLabel txt_encerrar;
    private javax.swing.JTextField txtacao;
    // End of variables declaration//GEN-END:variables
}
