/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import controllers.Chavoso;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import java.awt.Image;
import java.awt.Graphics;

/**
 *
 * @author David Alysson
 */
public class PrincipalChavoso extends javax.swing.JFrame {

    private static PrincipalChavoso p;
    
    public static PrincipalChavoso getInstancia(){       
        if(p == null){
            p = new PrincipalChavoso();
        }
        return p;
    }
    
    public static JDesktopPane getPainel(){
        return getInstancia().jdpprincipal;
    }
    
    
    /**
     * Creates new form PrincipalChavoso
     */
    public PrincipalChavoso() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpHeader = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_pesquisar_lab = new javax.swing.JLabel();
        btn_entregar_chave = new javax.swing.JLabel();
        btn_devolver_chave = new javax.swing.JLabel();
        btn_historico = new javax.swing.JLabel();
        btn_manutencao = new javax.swing.JLabel();
        btn_administracao = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        btn_minimizar = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/chavoso.png"));
        Image image = icon.getImage();
        jdpprincipal = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(image,0,0,getWidth(),getHeight(),this);

            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Chavoso");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jpHeader.setBackground(new java.awt.Color(241, 91, 77));

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema Chavoso™");

        btn_pesquisar_lab.setBackground(new java.awt.Color(45, 45, 45));
        btn_pesquisar_lab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_pesquisar_lab.setForeground(new java.awt.Color(255, 255, 255));
        btn_pesquisar_lab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_pesquisar_lab.setText("PESQUISAR LABORATÓRIO");
        btn_pesquisar_lab.setOpaque(true);
        btn_pesquisar_lab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pesquisar_labMouseClicked(evt);
            }
        });

        btn_entregar_chave.setBackground(new java.awt.Color(45, 45, 45));
        btn_entregar_chave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_entregar_chave.setForeground(new java.awt.Color(255, 255, 255));
        btn_entregar_chave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_entregar_chave.setText("ENTREGAR CHAVE");
        btn_entregar_chave.setOpaque(true);
        btn_entregar_chave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_entregar_chaveMouseClicked(evt);
            }
        });

        btn_devolver_chave.setBackground(new java.awt.Color(45, 45, 45));
        btn_devolver_chave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_devolver_chave.setForeground(new java.awt.Color(255, 255, 255));
        btn_devolver_chave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_devolver_chave.setText("DEVOLVER CHAVE");
        btn_devolver_chave.setOpaque(true);
        btn_devolver_chave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_devolver_chaveMouseClicked(evt);
            }
        });

        btn_historico.setBackground(new java.awt.Color(45, 45, 45));
        btn_historico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_historico.setForeground(new java.awt.Color(255, 255, 255));
        btn_historico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_historico.setText("HISTÓRICO");
        btn_historico.setOpaque(true);
        btn_historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_historicoMouseClicked(evt);
            }
        });

        btn_manutencao.setBackground(new java.awt.Color(45, 45, 45));
        btn_manutencao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_manutencao.setForeground(new java.awt.Color(255, 255, 255));
        btn_manutencao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_manutencao.setText("MANUTENÇÃO");
        btn_manutencao.setOpaque(true);
        btn_manutencao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_manutencaoMouseClicked(evt);
            }
        });

        btn_administracao.setBackground(new java.awt.Color(45, 45, 45));
        btn_administracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_administracao.setForeground(new java.awt.Color(255, 255, 255));
        btn_administracao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_administracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/config.png"))); // NOI18N
        btn_administracao.setOpaque(true);
        btn_administracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_administracaoMouseClicked(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(84, 84, 84));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 255, 255));
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_exit.setText("X");
        btn_exit.setOpaque(true);
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });

        btn_minimizar.setBackground(new java.awt.Color(84, 84, 84));
        btn_minimizar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_minimizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_minimizar.setText("-");
        btn_minimizar.setOpaque(true);
        btn_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizarMouseClicked(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(45, 45, 45));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_logout.setText("LOGOUT");
        btn_logout.setOpaque(true);
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpHeaderLayout = new javax.swing.GroupLayout(jpHeader);
        jpHeader.setLayout(jpHeaderLayout);
        jpHeaderLayout.setHorizontalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btn_entregar_chave, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_devolver_chave, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pesquisar_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122)))
                .addComponent(btn_manutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpHeaderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_administracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jpHeaderLayout.setVerticalGroup(
            jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHeaderLayout.createSequentialGroup()
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exit)
                    .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_entregar_chave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pesquisar_lab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_devolver_chave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_historico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_manutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_administracao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jdpprincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdpprincipal.setAutoscrolls(true);
        jdpprincipal.setPreferredSize(new java.awt.Dimension(1182, 600));

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jdpprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pesquisar_labMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pesquisar_labMouseClicked
        // TODO add your handling code here
        Chavoso.gerenciarJanelas(new BuscaLab());
    }//GEN-LAST:event_btn_pesquisar_labMouseClicked

    private void btn_entregar_chaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_entregar_chaveMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "Clicado");
        Chavoso.gerenciarJanelas(new EntregarChave());
    }//GEN-LAST:event_btn_entregar_chaveMouseClicked

    private void btn_devolver_chaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devolver_chaveMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new DevolverChave());
    }//GEN-LAST:event_btn_devolver_chaveMouseClicked

    private void btn_historicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_historicoMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new Historico());
    }//GEN-LAST:event_btn_historicoMouseClicked

    private void btn_manutencaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_manutencaoMouseClicked
        // TODO add your handling code here:
        Chavoso.gerenciarJanelas(new Manutencao());
    }//GEN-LAST:event_btn_manutencaoMouseClicked

    private void btn_administracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_administracaoMouseClicked
        // TODO add your handling code here:
        Chavoso.entrarAdmin();
        this.dispose();
    }//GEN-LAST:event_btn_administracaoMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void btn_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizarMouseClicked
        // TODO add your handling code here:
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_btn_minimizarMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
    */
    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalChavoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalChavoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalChavoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalChavoso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                getInstancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_administracao;
    private javax.swing.JLabel btn_devolver_chave;
    private javax.swing.JLabel btn_entregar_chave;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_historico;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_manutencao;
    private javax.swing.JLabel btn_minimizar;
    private javax.swing.JLabel btn_pesquisar_lab;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpprincipal;
    private javax.swing.JPanel jpHeader;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/icon.png")).getImage());
    }
    
}
